### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by KyryloKilin** [artela-network/artela-docs#9]
1. A broken link on the page: https://docs.artela.network/develop/get-started/sol-hello-world#36-test-the-smart-contract-and-aspect-integration 
![image](https://github.com/artela-network/artela-docs/assets/83702309/91e26b62-5db8-4131-b12e-2c631b601606)

2. A broken link on the page: https://docs.artela.network/develop/core-concepts/asolc#asolc-releases
![image](https://github.com/artela-network/artela-docs/assets/83702309/29b69f43-88aa-4edf-92f1-cba7a8a51c11)

3. A broken link on the page: https://docs.artela.network/develop/guides/reentrancy-guard#2-create-blockchain-accounts-optional
![image](https://github.com/artela-network/artela-docs/assets/83702309/16688df0-7ca4-4f6a-92fc-3d04313d539e)

**Comment by QiyuanMa** [comment]
Wow, thanks for becoming our first contributor! 

That's all great discovery. 

Please also open an issue under https://github.com/artela-network/contribute-to-artela, that's for future reward purposes. We'll update the docs as your suggested:)
